# Generated by Django 4.2.10 on 2024-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('published_date', models.CharField(max_length=50)),
                ('modified_date', models.CharField(max_length=50)),
                ('references', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('vector_string', models.CharField(max_length=100)),
            ],
        ),
    ]
