# Generated by Django 5.0.6 on 2024-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_app', '0002_alter_cveentry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveentry',
            name='base_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
