# Generated by Django 5.0.6 on 2024-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_app', '0003_cveentry_base_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveentry',
            name='affected_platform',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='assigner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='base_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='cwe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
