# Generated by Django 5.0.6 on 2024-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_app', '0004_cveentry_affected_platform_cveentry_assigner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RansomwareCVEEntry',
            fields=[
                ('cve_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('mitigation', models.TextField(blank=True)),
                ('ransomware', models.CharField(blank=True, max_length=500)),
                ('school', models.CharField(blank=True, max_length=500)),
                ('CISA', models.CharField(blank=True, max_length=500)),
                ('NVD', models.CharField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True)),
                ('ransomware_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ransomware_cve_list',
            },
        ),
        migrations.RemoveField(
            model_name='cveentry',
            name='vector_string',
        ),
        migrations.AlterModelTable(
            name='cveentry',
            table='entire_cve_list',
        ),
    ]
